### ISSUE TITLE
Update to OpenQASM 3.0

### ISSUE THREAD

**Issue by comp-phys-marc** [comp-phys-marc/qasm-ts#2]
This parser was written to parse OpenQASM 2.0. OpenQASM 3.0 introduced more computational logic, gate calibrations and embedded pulse-level definitions to the spec as documented [here](https://qiskit.github.io/openqasm/intro.html). I would love help updating to the 3.0 spec.

**Comment by comp-phys-marc** [comment]
Note: OpenQASM 3.0 documentation has been moved [here](https://github.com/openqasm/openqasm/blob/main/source/intro.rst).

**Comment by comp-phys-marc** [comment]
A [new branch](https://github.com/comp-phys-marc/qasm-ts/tree/open-qasm-3.0) has been created wherein support for identifiers that start with capital letters, underscores, and unicode characters has been added.

**Comment by seankim658** [comment]
Organizing the 3.0 changes into a check mark list to keep track of progress: 

- [x] OpenQASM 3.0 headers (Circuit header, pg. 8)
- [ ] New preferred syntax for quantum and classical registers (Quantum and classical registers, pg. 9)
- [ ] Identifiers can now begin with capital letters, underscores, and other unicode characters (except for π which is reserved for the pi constant) (Names of gates, variables, and constants, pg. 9)
- [ ] `CX` is no longer a keyword, update for the use of a `ctrl @` gate modifier (Basic operations, pg. 9)
- [ ] Support alternative syntax for measurements, like so `c[d] = measure q[j]` (Basic operations, pg. 10)
- [ ] Other ways to define unitary operations (Gate declarations, pg. 10)
- [ ] New ways to define subroutines (Gate declarations, pg. 10) 
- [ ] `opaque` declarations are no longer needed and should be ignored by OpenQASM 3 compilers (Opaque definitions, pg. 11)
- [ ] OpenQASM 3 introduces a means of explicitly declaring which circuit output  are to be produced as output or taken as input; if a circuit does not specify either an input or an output, by default, it produces all of its classical stored variables as output (Circuit output, pg. 11)  

As of now this is a non-exhaustive list. As things are worked through the paper/documentation site will need to be reviewed more thoroughly to catch everything.

**Comment by seankim658** [comment]
The support for the new `measure` syntax has been pushed but I found [this](https://github.com/openqasm/openqasm/blob/229212fad2400d0b9f76bdab96bd748c199839b8/examples/adder.qasm#L43) example of a `measure` statement with what looks like as an index range that we do not currently cover.

**Comment by seankim658** [comment]
It doesn't look like we support the `opaque` gate declaration at all in the existing 2.0 lexer/parser (pages 6/7 of the 2.0 spec [paper](https://arxiv.org/pdf/1707.03429)). Opaque declarations are ignored in OpenQASM 3, I think we need to retroactively add support for that? Seems like right now it gets parsed as an `Id` (4) token. Adding lexer support (and a token for that) would allow for version 3 parsing to ignore that and leave it out of the resulting syntax tree.
